data_sources:
  <%= ENV["BLAZER_DATABASE_LABEL"] %>:
    url: <%= ENV["BLAZER_DATABASE_URL"] %>
    timeout: 15
    # use_transaction: true
    cache: 60 # minutes
    # linked_columns:
    #   title: "http://us.imdb.com/M/title-exact?{value}"
    #   zip_code: "https://www.google.com/search?q={value}"
    # smart_columns:
    #   occupation_id: "SELECT id, name FROM occupations WHERE id IN {value}"
    #   movie_id: "SELECT id, title FROM movies WHERE id IN {value}"
    #   genre_id: "SELECT id, name FROM genres WHERE id IN {value}"
    # smart_variables:
    #   movie_id: "SELECT id, title FROM movies ORDER BY title ASC"
    #   occupation_id: "SELECT id, name FROM occupations ORDER BY name ASC"
    #   genre_id: "SELECT id, name FROM genres ORDER BY name ASC"
  <%= ENV["BLAZER_DATABASE2_LABEL"] %>:
    url: <%= ENV["BLAZER_DATABASE2_URL"] %>
    cache: 60 # minutes
  <%= ENV["BLAZER_DATABASE3_LABEL"] %>:
    url: <%= ENV["BLAZER_DATABASE3_URL"] %>
    cache: 60 # minutes
  <%= ENV["BLAZER_DATABASE4_LABEL"] %>:
    url: <%= ENV["BLAZER_DATABASE4_URL"] %>
    cache: 60 # minutes
  <%= ENV["BLAZER_DATABASE5_LABEL"] %>:
    url: <%= ENV["BLAZER_DATABASE5_URL"] %>
    cache: 60 # minutes
  <%= ENV["BLAZER_DATABASE6_LABEL"] %>:
    url: <%= ENV["BLAZER_DATABASE6_URL"] %>
    cache: 60 # minutes

time_zone: "Eastern Time (US & Canada)"
audit: true
